# Usage:
#   conda env create -f conda-env.yaml
# or:
#   conda env update -v -n [base] -f conda-env.yml [--prune]
# This does not install CNVkit itself. Use pip to install either a stable release from
# PyPI (pip install cnvkit), or this local repo (pip install -e .).
name: cnvkit
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.10
    - atlas # [not osx]
    - bioconductor-dnacopy
    - biopython >=1.85
    - matplotlib >=3.8.3
    - numpy >=2.2.3
    - pandas >=2.2.3
    - pomegranate >=1.0.0
    - pyparsing >=3.1.2,<3.3.0
    - pyfaidx >=0.8.1.3
    - pysam >=0.23.0
    - pytest
    - reportlab >=4.3.1
    - ruff
    - scikit-learn >=1.5.0
    - scipy >=1.14.1
    - tox

