# Usage:
#   conda env create -f conda-env.yaml
# or:
#   conda env update -v -n [base] -f conda-env.yml [--prune]
# This does not install CNVkit itself. Use pip to install either a stable release from
# PyPI (pip install cnvkit), or this local repo (pip install -e .).
name: cnvkit
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.10
    - atlas # [not osx]
    - bioconductor-dnacopy
    - biopython >=1.83
    - matplotlib >=3.8.0
    - numpy >=1.26.4
    - pandas >=2.1.4
    - pomegranate >=1.0.0
    - pyparsing >=3.1.0,<3.3.0
    - pyfaidx >=0.8.0
    - pysam >=0.22.0
    - pytest
    - reportlab >=3.6.13
    - ruff
    - scikit-learn >=1.5.0
    - scipy >=1.11.4
    - tox

