[project]
name = "CNVkit"
description = "Copy number variation toolkit for high-throughput sequencing."
readme = "README.rst"
#license = "Apache-2.0"
license = {text = "Apache-2.0"}
authors = [
  {name = "Eric Talevich", email = "etal@users.noreply.github.com"}
]
maintainers = [
  {name = "Eric Talevich", email = "etal@users.noreply.github.com"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Healthcare Industry",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: POSIX",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Unix",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Topic :: Scientific/Engineering :: Medical Science Apps.",
  "Topic :: Scientific/Engineering :: Visualization"
]
requires-python = ">=3.7"
#dependencies = [
#"biopython >= 1.62",
#"matplotlib >= 1.3.1",
#"numpy >= 1.9",
#"pandas >= 0.23.3",
#"pomegranate >= 0.14.0",
#"pyfaidx >= 0.4.7",
#"pysam >= 0.10.0",
#"reportlab >= 3.0",
#"scikit-learn",
#"scipy >= 0.15.0"
#]
dynamic = ["version", "dependencies", "optional-dependencies"]

[project.urls]
homepage = "https://github.com/etal/cnvkit"
documentation = "https://readthedocs.org"
repository = "https://github.com/etal/cnvkit"
changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

#[project.optional-dependencies]
#test = [
#  "pytest < 5.0.0",
#  "pytest-cov[all]"
#]

[project.scripts]
"cnvkit.py" = "cnvlib.cnvkit:main"
#"cnv_annotate.py" = "scripts.cnv_annotate"
#"cnv_expression_correlate.py" = "scripts.cnv_expression_correlate"
#"cnv_updater.py" = "scripts.cnv_updater"
#"genome_instability_index.py" = "scripts.genome_instability_index"
#"guess_baits.py" = "scripts.guess_baits"
#"reference2targets.py" = "scripts.reference2targets"
#"skg_convert.py" = "scripts.skg_convert"
#"snpfilter.sh" = "scripts/snpfilter.sh"
# XXX TODO -- move these files under cnvlib or another folder?
#spam-cli = "spam:main_cli"
# -- from setup.py --
#   scripts=[join(DIR, 'cnvkit.py')] + glob(join(DIR, 'scripts/*.py')),
#   install_requires=install_requires,

[build-system]
# Minimum requirements for the build system to execute (PEP 508)
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["cnvlib", "cnvlib.segmentation", "skgenome", "skgenome.tabio"]

[tool.setuptools.dynamic]
version = {attr = "cnvlib._version.__version__"}
dependencies = {file = "requirements.txt"}
optional-dependencies = {test = {file = "requirements-test.txt"}}

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["error"]

[tool.coverage.run]
branch = true
source = ["cnvlib", "skgenome", "tests"]

[tool.coverage.paths]
source = ["cnvlib", "skgenome"]

[tool.mypy]
python_version = "3.7"
files = ["src/flask"]
show_error_codes = true
pretty = true
#strict = true
allow_redefinition = true
disallow_subclassing_any = true
#disallow_untyped_calls = true
#disallow_untyped_defs = true
#disallow_incomplete_defs = true
no_implicit_optional = true
local_partial_types = true
#no_implicit_reexport = true
strict_equality = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
#warn_return_any = true
#warn_unreachable = true

[[tool.mypy.overrides]]
#module = [
    # "asgiref.*",
    # "blinker.*",
    # "dotenv.*",
    # "cryptography.*",
    # "importlib_metadata",
#]
ignore_missing_imports = true
