package:
  name: cnvkit
  version: "dev"

source:
  path: ../../

build:
  number: 0
  skip: False

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - atlas # [not osx]
    - biopython >=1.79
    - matplotlib >=3.5.1
    - numpy >=1.21.6
    - pandas >=1.3.5
    - pomegranate ==0.14.8
    - python-dateutil >=2.5.0
    - pyfaidx >=0.6.4
    - pysam >=0.17.0
    - reportlab >=3.6.8
    - scikit-learn
    - scipy >=1.7.3
    - networkx >=2.4
    - bioconductor-dnacopy
#   - joblib <1.0

test:
  imports:
    - cnvlib
    - skgenome
  commands:
    - cnvkit.py -h

about:
  home: https://github.com/etal/cnvkit
  license: Apache License 2.0
  summary: Copy number variant detection from high-throughput sequencing
