package:
  name: cnvkit
  version: "dev"

source:
  path: ../../

build:
  number: 0
  skip: False
  run_exports:
    - {{ pin_subpackage('conda', max_pin="x.x") }}


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - atlas # [not osx]
    - bioconductor-dnacopy
    - biopython >=1.80
    - matplotlib >=3.5.2
    - numpy >=1.24.2
    - pandas >=1.5.3
    - pomegranate >=0.14.8, <=0.14.9
    - pyfaidx >=0.7.1
    - pysam >=0.20.0
    - reportlab >=3.6.12
    - scikit-learn >=1.1.0
    - scipy >=1.10.1

test:
  imports:
    - cnvlib
    - skgenome
  commands:
    - cnvkit.py -h

about:
  home: https://github.com/etal/cnvkit
  license: Apache License 2.0
  summary: Copy number variant detection from high-throughput sequencing
